name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '2.5', '2.6', '2.7', '3.0' ]
        include:
          - ruby-version: '3.0'
            coverage: 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - uses: amancevice/setup-code-climate@v0
        name: CodeClimate setup
        if: ${{ matrix.coverage == 'true' }}
        with:
          cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: CodeClimate before-build
        run: cc-test-reporter before-build
        if: ${{ matrix.coverage == 'true' }}
        continue-on-error: true
      - name: Run tests
        env:
          COVERAGE: ${{ matrix.coverage }}
        run: bundle exec rake
      - name: CodeClimate after-build
        run: cc-test-reporter after-build
        if: ${{ matrix.coverage == 'true' }}
        continue-on-error: true
